#environment:
language: node_js
node_js:
  - 12.12.0
addons:
  chrome: stable

#build:
install:
  - npm install
script:
  - npm run test-lib
  - npm run build-lib
  - npm run build-app

#deployment:
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: master
